build:
    environment:
        php:
            version: 5.6.9
    dependencies:
        before:
            - sudo apt-get install jpegoptim
            - sudo apt-get install pngquant
            - sudo apt-get install gifsicle
            - sudo cp /usr/bin/jpegoptim /usr/local/bin/jpegoptim
            - sudo chmod a+x /usr/local/bin/jpegoptim
            - sudo cp /usr/bin/pngquant /usr/local/bin/pngquant
            - sudo chmod a+x /usr/local/bin/pngquant
            - sudo cp /usr/bin/gifsicle /usr/local/bin/gifsicle
            - sudo chmod a+x /usr/local/bin/gifsicle

    tests:
        before:
            - cp .env.travis .env
            - composer install --no-interaction
            - mkdir storage/app/compressed
            - mkdir storage/app/resized
            - mkdir storage/app/remote
            - chmod -R 777 storage