build:
    environment:
        php:
            version: 5.6.9
    tests:
        before:
            - cp .env.travis .env
            - mkdir storage/app/compressed
            - mkdir storage/app/resized
            - mkdir storage/app/remote
            - chmod -R 777 storage