build:
    environment:
        php:
            version: 5.6.9
    dependencies:
        before:
            - sudo apt-get install jpegoptim
            - sudo apt-get install pngquant
            - sudo apt-get install gifsicle

    tests:
        before:
            - cp .env.travis .env
            - composer install --no-interaction
            - mkdir storage/app/compressed
            - mkdir storage/app/resized
            - mkdir storage/app/remote
            - chmod -R 777 storage