language: php

php:
  - 5.6

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - sudo apt-get install jpegoptim
  - sudo apt-get install pngquant
  - sudo apt-get install gifsicle
  - sudo ln -s /usr/bin/ /usr/local/bin
  - /usr/local/bin/jpegoptim -V

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - chmod -R 777 storage
  - mkdir storage/app/compressed
  - mkdir storage/app/remote
  - mkdir storage/app/resized
  - chmod -R 777 storage
  - jpegoptim -v

addons:
  hosts:
  - imageoptim.dev

script: vendor/bin/phpunit